# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AddressAutofillSDKSampleSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AddressAutofillSDKSampleSwift
  pod 'Address-Autofill-iOS'

  target 'AddressAutofillSDKSampleSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AddressAutofillSDKSampleSwiftUITests' do
    # Pods for testing
  end

end
