# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AddressAutofillSDKSampleObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AddressAutofillSDKSampleObjc
  pod 'Address-Autofill-iOS'

  target 'AddressAutofillSDKSampleObjcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AddressAutofillSDKSampleObjcUITests' do
    # Pods for testing
  end

end
